.github/workflows/publish.yml

Let's try this again with a hopefully fixed github action.

Release 4.0.1 - the 2nd

---

CHANGELOG.md

Release 4.0.2 

---

CHANGELOG.md

re-try to publish release - 4.0.3

Redo - Release FLATLAND-RL / 4.0.3

---

rendering/make_video_ffmpeg.txt

Rendering folder is not used. Descriptions in txt file are also contained in `examples/misc/generate_video/video_generation.md`
None.
changes, describe them under the `[Unreleased]` tag in `CHANGELOG.md`.

Remove rendering folder

---

README.md

- **an** open-source toolkit ...
indefinite article "an"
changes, describe them under the `[Unreleased]` tag in `CHANGELOG.md`.

fix: README.md indefinite article before a vowel sound

---

tests/test_flatland_malfunction.py

- **sche**~u~dule
- malfun**ctio**ning

Fix spelling in test_flatland_malfunction py

---

CHANGELOG.md

Changelog 4.0.5.

---

.github/workflows/checks.yml

Enable checks workflow on all prs.
--

Enable checks workflow on all prs.

---

.github/workflows/checks.yml
.github/workflows/main.yml
tox.ini

161 Split unit tests and slow ml tests in tox for transparency and parallelism.

---

.github/workflows/checks.yml
.github/workflows/main.yml
.github/workflows/publish.yml
tox.ini

Fix tox gh actions.
Close #161 

Fix tox gh actions.

---

benchmarks/benchmark_episodes.py

Fix benchmarks.

---

.github/workflows/main.yml

Fix main gh wf.

---

CHANGELOG.md

Release 4.0.6.

---

CHANGELOG.md

Release 4.1.0.

---

flatland/utils/graphics_pil.py

Offset to improve visibility of agent debug number.

Improved offset for agent debug.

---

.github/workflows/checks.yml
.github/workflows/main.yml
benchmarks/benchmark_episodes_deadlock_avoidance.py
tox.ini

Add regression tests running flatland-baselines/deadloack-avoidance (DLA) against saved trajectories verifying success rate, actions and positions.
In preparation for #87 

Add regression DLA against saved trajectories.

---

CHANGELOG.md

Release 4.1.1

---

.github/workflows/checks.yml
.github/workflows/main.yml
flatland/envs/persistence.py
flatland/envs/rail_env.py
flatland/envs/step_utils/state_machine.py
flatland/envs/step_utils/states.py

*  Use fastenum.Enum instead of enum.Intenum for TrainState. 
* Re-use StateTransitionSignals objects.
* Remove obsolete single file artifact upload as single files get zipped all the same during artifact upload.
Part of #206 

Performance Tuning step function part III: TrainState/StateTransitionSignals data types and object lifecycle.

---

README.md

Add Flatland Association and Flatland Community to credits.

Add Flatland Association and Flatland Community to credits.

---

CHANGELOG.md

Release 4.1.2

---

flatland/trajectories/policy_runner.py
flatland/trajectories/trajectories.py
tests/trajectories/test_trajectories.py

Trajectory API fork: load the latest snapshot and running from there instead of from beginning.
Closes #240.

feature: Improve Trajectory API fork: load the latest snapshot and run from there instead of from beginning.

---

flatland/core/effects_generator.py
flatland/core/transition_map.py
flatland/envs/grid4_generators_utils.py
flatland/envs/malfunction_effects_generators.py
flatland/envs/persistence.py
flatland/envs/rail_env.py
flatland/envs/rail_generators.py
flatland/envs/rail_grid_transition_map.py
tests/test_flatland_core_grid4_generators_util.py
tests/test_flatland_envs_rail_env_effects_generator.py

* Encapsulate random state in generators.
* Refactor malfunction generation as effects generator.
Closes #194 

refactor: malfunction generation as effects generator.

---

CHANGELOG.md

docs: changelog v4.2.0.

---

flatland/env_generation/env_generator.py
flatland/envs/rail_env.py
flatland/envs/rewards.py
flatland/trajectories/policy_runner.py
tests/test_multi_speed.py
tests/test_rewards.py

* refactor: extract interface from default rewards and add cumulate and empty.
* feature: add rewards arg to env generator and pass through rewards from policy runner.
* feature: add basic morl rewards function for illustration.
Closes #234 .

feature: basic support for Multi-Objective Reinforcement Learning (MORL).

---

flatland/envs/rewards.py
flatland/evaluators/trajectory_evaluator.py
flatland/evaluators/trajectory_grid_evaluator.py
flatland/trajectories/policy_grid_runner.py
flatland/trajectories/policy_runner.py
flatland/trajectories/trajectories.py
pyproject.toml
tests/regression/test_policy_grid_runner.py
tests/regression/test_policy_grid_runner_evaluator.py
tests/test_rewards.py
tests/trajectories/test_trajectories.py
tox.ini

* feature: make policy grid runner a click command.
* feature: add script flatland-trajectory-generate-from-metadata.
* feature: add grid evaluator
* feature: add option to pass rewards to trajectory (grid) evaluator and policy (grid) runner.
* feature: add `PunctualityRewards`, see https://github.com/flatland-association/flatland-benchmarks/issues/248
* ~feature: add `NetworkImpactRewards`, see https://github.com/flatland-association/flatland-benchmarks/issues/248~
*  feature: add option to pass scenario score aggregator and report to trajectory grid evaluator.
*  refactor: MORL to use tuples instead of lists.
Closes #264 

feature: offline evaluation.

---

flatland/trajectories/trajectories.py

* improve actions, rewards. etc. collection by inserting all new rows into pandas df after policy run instead of in every step.

perf(trajectories): improve collecting during policy run.

---

.github/workflows/checks.yml

Update dependency post merge flatland baselines

---

.github/workflows/checks.yml

ci: fix condition run benchmarks on main.

---

CHANGELOG.md

chore: Release Notes 4.2.2.

---

.github/workflows/publish-test.yml
.github/workflows/publish.yml

ci: fix tests in publish workflows.
